name: MyPy check

on:
  push:
    branches: [ master, "feature/*", "bugfix/*", "maintenance/*" ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: jpetrucciani/mypy-check@0.991
      with:
        path: pyhanko
        requirements: "-e .[mypy,testing,pkcs11,xmp,opentype,image-support,async_http,extra_pubkey_algs] --config-settings editable_mode=strict"
